### ISSUE TITLE
No average time showing

### ISSUE THREAD

**Issue by DTRW919** [CubeStuffs/CubeTime#56] opened 2022-05-04 22:43 UTC
When restarting the app, I cannot view my averages on the timer screen until I finish a solve.

**Comment by pdtxie** [comment] 2022-05-04 23:00
Is this in build 1.2.1? Might be caused by some changes to TimerView @xbjfk please confirm.

**Comment by xbjfk** [comment] 2022-05-06 05:42
should be fixed in db4b024d009d63d20baf3fe25e8f24e7378026cb, we will add an update to the app store soon

**Closed by xbjfk** 2022-05-06 05:42 UTC
